import { CountryData } from '@/types/geo';

export const GLOBAL_COUNTRIES: CountryData[] = [
  {
    id: 'country-eg',
    code: 'EG',
    nameEn: 'Egypt',
    nameAr: 'مصر',
    regionTerminologyEn: 'Governorate',
    regionTerminologyAr: 'محافظة',
    regions: [
      {
        id: 'reg-sohag',
        nameEn: 'Sohag',
        nameAr: 'سوهاج',
        cities: [
          {
            id: 'city-sohag-center',
            nameEn: 'Sohag City',
            nameAr: 'مدينة سوهاج',
            soilTypeEn: 'Alluvial Silt Loam (Deep Nile Valley Horizon)',
            soilTypeAr: 'طمي نيلي ناعم عالي الخصوبة',
            climateZoneEn: 'Upper Egypt Subtropical Arid Basin',
            climateZoneAr: 'حوض صعيد مصر شبه المداري الجاف',
            avgGdd: 2850,
            avgAnnualRainfallMm: 18,
            primaryCropsEn: ['Yellow Onion', 'Durum Wheat', 'Summer Tomato'],
            primaryCropsAr: ['بصل صعيدي جاف', 'قمح صلب', 'طماطم صيفية'],
            coordinates: { lat: 26.556, lng: 31.694 },
          },
          {
            id: 'city-akhmim',
            nameEn: 'Akhmim',
            nameAr: 'أخميم',
            soilTypeEn: 'Fine Silty Clay with Moderate Potassium',
            soilTypeAr: 'طيني غريني غني بالبوتاسيوم الطبيعي',
            climateZoneEn: 'Hyper-Arid Upper Nile Valley',
            climateZoneAr: 'وادي النيل العلوي شديد الجفاف',
            avgGdd: 2880,
            avgAnnualRainfallMm: 15,
            primaryCropsEn: ['High-Brix Cluster Tomato', 'Sugarcane', 'Broad Bean'],
            primaryCropsAr: ['طماطم عنقودية عالية السكريات', 'قصب السكر', 'فول بلدي'],
            coordinates: { lat: 26.565, lng: 31.745 },
          },
          {
            id: 'city-tahta',
            nameEn: 'Tahta',
            nameAr: 'طهطا',
            soilTypeEn: 'Sandy Loam Reclaimed Perimeter',
            soilTypeAr: 'رملي طمي حافة صحراوية مستصلحة',
            climateZoneEn: 'Western Desert Fringe Subtropical',
            climateZoneAr: 'حافة الصحراء الغربية شبه المدارية',
            avgGdd: 2820,
            avgAnnualRainfallMm: 16,
            primaryCropsEn: ['Export Onions', 'Garlic', 'Alfalfa'],
            primaryCropsAr: ['بصل تصديري', 'ثوم بلدي', 'برسيم حجازي'],
            coordinates: { lat: 26.768, lng: 31.502 },
          },
          {
            id: 'city-girga',
            nameEn: 'Girga',
            nameAr: 'جرجا',
            soilTypeEn: 'Heavy Riverine Silt Horizon',
            soilTypeAr: 'طمي نهري ثقيل عالي المادة العضوية',
            climateZoneEn: 'Southern Upper Valley Microclimate',
            climateZoneAr: 'وادي الصعيد الأوسط',
            avgGdd: 2900,
            avgAnnualRainfallMm: 14,
            primaryCropsEn: ['Sugar Beet', 'Wheat', 'Early Melons'],
            primaryCropsAr: ['بنجر سكر', 'قمح ديورم', 'بطيخ مبكر'],
            coordinates: { lat: 26.338, lng: 31.894 },
          },
        ],
      },
      {
        id: 'reg-qena',
        nameEn: 'Qena',
        nameAr: 'قنا',
        cities: [
          {
            id: 'city-qena-center',
            nameEn: 'Qena City',
            nameAr: 'مدينة قنا',
            soilTypeEn: 'Silty Loam over Sand Sub-strata',
            soilTypeAr: 'طمي غريني فوق طبقات رملية',
            climateZoneEn: 'High Thermal Sum Arid Corridor',
            climateZoneAr: 'ممر حراري جاف مرتفع التراكم الحراري',
            avgGdd: 3050,
            avgAnnualRainfallMm: 12,
            primaryCropsEn: ['Sugarcane', 'Sweet Hibiscus', 'Tomato'],
            primaryCropsAr: ['قصب السكر', 'كركديه صعيدي', 'طماطم'],
            coordinates: { lat: 26.155, lng: 32.716 },
          },
          {
            id: 'city-nag-hammadi',
            nameEn: 'Nag Hammadi',
            nameAr: 'نجع حمادي',
            soilTypeEn: 'Nile Deep Loam Basin',
            soilTypeAr: 'طمي نيلي عميق متوازن النفاذية',
            climateZoneEn: 'Upper Egypt River Bend',
            climateZoneAr: 'حوض ثنية النيل',
            avgGdd: 3000,
            avgAnnualRainfallMm: 13,
            primaryCropsEn: ['Sugarcane', 'Maize', 'Sesame'],
            primaryCropsAr: ['قصب السكر', 'ذرة شامية', 'سمسم أبيض'],
            coordinates: { lat: 26.049, lng: 32.241 },
          },
        ],
      },
      {
        id: 'reg-luxor',
        nameEn: 'Luxor',
        nameAr: 'الأقصر',
        cities: [
          {
            id: 'city-luxor-center',
            nameEn: 'Luxor City',
            nameAr: 'مدينة الأقصر',
            soilTypeEn: 'Alluvial Loam with Desert Edge Sand',
            soilTypeAr: 'طمي نهري مختلط برمال الصحراء الشرقية',
            climateZoneEn: 'Arid Valley with High Solar Irradiance',
            climateZoneAr: 'وادي جاف عالي الإشعاع الشمسي',
            avgGdd: 3120,
            avgAnnualRainfallMm: 10,
            primaryCropsEn: ['Export Table Grapes', 'Early Watermelon', 'Dates'],
            primaryCropsAr: ['عنب مائدة تصديري', 'بطيخ مبكر', 'نخيل بلح'],
            coordinates: { lat: 25.687, lng: 32.639 },
          },
          {
            id: 'city-esna',
            nameEn: 'Esna',
            nameAr: 'إسنا',
            soilTypeEn: 'Deep Clay Loam near Irrigation Barrages',
            soilTypeAr: 'طيني طمي عميق حول قناطر إسنا',
            climateZoneEn: 'Southern Valley Corridor',
            climateZoneAr: 'ممر جنوب الوادي الزراعي',
            avgGdd: 3140,
            avgAnnualRainfallMm: 8,
            primaryCropsEn: ['Export Tomato', 'Sugarcane', 'Bananas'],
            primaryCropsAr: ['طماطم تجفيف وتصدير', 'قصب السكر', 'موز'],
            coordinates: { lat: 25.293, lng: 32.553 },
          },
        ],
      },
      {
        id: 'reg-aswan',
        nameEn: 'Aswan',
        nameAr: 'أسوان',
        cities: [
          {
            id: 'city-aswan-center',
            nameEn: 'Aswan City',
            nameAr: 'مدينة أسوان',
            soilTypeEn: 'Sandy Loam with Granite/Basalt Inclusions',
            soilTypeAr: 'رملي طمي مع معادن جرانيتية وبازلتية',
            climateZoneEn: 'Hyper-Arid Tropics of Cancer',
            climateZoneAr: 'مدار السرطان شديد الجفاف والحرارة',
            avgGdd: 3400,
            avgAnnualRainfallMm: 5,
            primaryCropsEn: ['Dry Dates (Sakkoti/Gargoda)', 'Medicinal Henna', 'Hibiscus'],
            primaryCropsAr: ['تمور جافة (سكوتي/برتمودا)', 'حناء طبيعية', 'كركديه'],
            coordinates: { lat: 24.088, lng: 32.899 },
          },
          {
            id: 'city-toshka',
            nameEn: 'Toshka Precision Sector',
            nameAr: 'مشروع توشكى الزراعي',
            soilTypeEn: 'Calcareous Loamy Sand with Silty Deposits',
            soilTypeAr: 'رملي جيري طمي خفيف عالي النفاذية',
            climateZoneEn: 'Continental Desert Precision VRI',
            climateZoneAr: 'صحراوي قاري محوري متغير الري (VRI)',
            avgGdd: 3350,
            avgAnnualRainfallMm: 2,
            primaryCropsEn: ['Durum Wheat', 'Medjool Dates', 'Export Jojoba'],
            primaryCropsAr: ['قمح صلب عالي البروتين', 'نخيل مجدول', 'جوجوبا'],
            coordinates: { lat: 22.583, lng: 31.842 },
          },
        ],
      },
      {
        id: 'reg-beheira',
        nameEn: 'Beheira',
        nameAr: 'البحيرة',
        cities: [
          {
            id: 'city-wadi-natrun',
            nameEn: 'Wadi El Natrun',
            nameAr: 'وادي النطرون',
            soilTypeEn: 'Sandy Clay Loam with Eocene Aquifer Source',
            soilTypeAr: 'رملي طيني طمي يعتمد على خزان الإيوسين',
            climateZoneEn: 'Semi-Arid Western Delta Margins',
            climateZoneAr: 'شبه جاف أطراف الدلتا الغربية',
            avgGdd: 2480,
            avgAnnualRainfallMm: 45,
            primaryCropsEn: ['Cluster Tomato', 'Olive Orchards', 'Citrus Grapes'],
            primaryCropsAr: ['طماطم شيري وعنقودية', 'زيتون مائدة وزيت', 'موالح وعنب'],
            coordinates: { lat: 30.412, lng: 30.345 },
          },
          {
            id: 'city-nubariya',
            nameEn: 'Nubariya Agro Hub',
            nameAr: 'النوبارية',
            soilTypeEn: 'Modern Reclaimed Calcareous Sand-Loam',
            soilTypeAr: 'رملي جيري مستصلح حديث بالتنقيط',
            climateZoneEn: 'Mediterranean Delta Transition',
            climateZoneAr: 'انتقالي ساحلي متوسطي إلى صحراوي',
            avgGdd: 2420,
            avgAnnualRainfallMm: 65,
            primaryCropsEn: ['Strawberries (Fortuna)', 'Potatoes', 'Sweet Corn'],
            primaryCropsAr: ['فراولة فورتونا تصديرية', 'بطاطس تصنيع وتصدير', 'ذرة سكرية'],
            coordinates: { lat: 30.666, lng: 30.066 },
          },
        ],
      },
      {
        id: 'reg-newvalley',
        nameEn: 'New Valley',
        nameAr: 'الوادي الجديد',
        cities: [
          {
            id: 'city-kharga',
            nameEn: 'El Kharga Oasis',
            nameAr: 'واحة الخارجة',
            soilTypeEn: 'Nubian Sandstone Derived Sandy Loam',
            soilTypeAr: 'طمي رملي مشتق من الحجر الرملي النوبي',
            climateZoneEn: 'Deep Western Desert Oasis',
            climateZoneAr: 'واحات الصحراء الغربية العميقة',
            avgGdd: 3100,
            avgAnnualRainfallMm: 4,
            primaryCropsEn: ['Semi-Dry Dates (Siwi)', 'Wheat', 'Aromatic Herbs'],
            primaryCropsAr: ['تمور نصف جافة (صعيدي/سيوي)', 'قمح', 'نباتات عطرية'],
            coordinates: { lat: 25.451, lng: 30.546 },
          },
          {
            id: 'city-farafra',
            nameEn: 'Farafra Megafarm Belt',
            nameAr: 'واحة الفرافرة (المليون ونصف فدان)',
            soilTypeEn: 'Deep Sandy Soil with Neutral pH Horizon',
            soilTypeAr: 'تربة رملية عميقة متعادلة الحموضة',
            climateZoneEn: 'Hyper-Arid Solar Radiation Maximum',
            climateZoneAr: 'صحراوي جاف أقصى معدل سطوع شمسي',
            avgGdd: 3020,
            avgAnnualRainfallMm: 6,
            primaryCropsEn: ['Alfalfa Hay', 'Canola Oilseed', 'Barley'],
            primaryCropsAr: ['دريس برسيم حجازي', 'كانولا بذور زيتية', 'شعير'],
            coordinates: { lat: 27.058, lng: 27.971 },
          },
        ],
      },
    ],
  },
  {
    id: 'country-sa',
    code: 'SA',
    nameEn: 'Saudi Arabia',
    nameAr: 'المملكة العربية السعودية',
    regionTerminologyEn: 'Province',
    regionTerminologyAr: 'منطقة',
    regions: [
      {
        id: 'reg-riyadh',
        nameEn: 'Riyadh Province',
        nameAr: 'منطقة الرياض',
        cities: [
          {
            id: 'city-alkharj',
            nameEn: 'Al-Kharj Agricultural Belt',
            nameAr: 'محافظة الخرج',
            soilTypeEn: 'Engineered Loamy Sand & Hydroponic Substrates',
            soilTypeAr: 'تربة رملية طميية وأوساط هيدروبونيك متقدمة',
            climateZoneEn: 'Central Najd Desert Plateau',
            climateZoneAr: 'هضبة نجد الصحراوية الجافة',
            avgGdd: 3150,
            avgAnnualRainfallMm: 85,
            primaryCropsEn: ['Greenhouse Bell Pepper', 'Greenhouse Tomato', 'Hydroponic Greens'],
            primaryCropsAr: ['فلفل رومي بيوت محمية', 'طماطم هيدروبونيك', 'ورقيات'],
            coordinates: { lat: 24.155, lng: 47.311 },
          },
          {
            id: 'city-wadi-dawasir',
            nameEn: 'Wadi Ad-Dawasir',
            nameAr: 'وادي الدواسر',
            soilTypeEn: 'Deep Sandy Bed with Modern Pivot Grids',
            soilTypeAr: 'طبقات رملية عميقة مع دوائر ري محوري',
            climateZoneEn: 'Southern Najd Arid Basin',
            climateZoneAr: 'حوض جنوب نجد عالي التبخر',
            avgGdd: 3300,
            avgAnnualRainfallMm: 40,
            primaryCropsEn: ['Potatoes', 'Silage Maize', 'Watermelons'],
            primaryCropsAr: ['بطاطس صناعية', 'سيلاج ذرة', 'حبحب وادي الدواسر'],
            coordinates: { lat: 20.452, lng: 44.821 },
          },
        ],
      },
      {
        id: 'reg-qassim',
        nameEn: 'Al-Qassim Province',
        nameAr: 'منطقة القصيم',
        cities: [
          {
            id: 'city-buraidah',
            nameEn: 'Buraidah',
            nameAr: 'بريدة',
            soilTypeEn: 'Fertile Oasis Sandy Clay Layer',
            soilTypeAr: 'طبقات واحات طينية رملية خصبة',
            climateZoneEn: 'Continental Dry Thermal Zone',
            climateZoneAr: 'مناخ قاري جاف مع تذبذب حراري',
            avgGdd: 2980,
            avgAnnualRainfallMm: 110,
            primaryCropsEn: ['Sukkari Dates', 'Wheat', 'Seedless Grapes'],
            primaryCropsAr: ['تمور سكري ملكي', 'قمح', 'عنب بدون بذور'],
            coordinates: { lat: 26.326, lng: 43.975 },
          },
          {
            id: 'city-unaizah',
            nameEn: 'Unaizah',
            nameAr: 'عنيزة',
            soilTypeEn: 'Permeable Loam over Sand Sub-base',
            soilTypeAr: 'طمي نفاذ ممتاز الصرف الزراعي',
            climateZoneEn: 'Arid Inland Oasis',
            climateZoneAr: 'واحات داخلية جافة',
            avgGdd: 2960,
            avgAnnualRainfallMm: 105,
            primaryCropsEn: ['Citrus', 'Pomegranates', 'Greenhouse Cucumbers'],
            primaryCropsAr: ['حمضيات', 'رمان القصيم', 'خيار محمي'],
            coordinates: { lat: 26.091, lng: 43.991 },
          },
        ],
      },
    ],
  },
  {
    id: 'country-us',
    code: 'US',
    nameEn: 'United States',
    nameAr: 'الولايات المتحدة',
    regionTerminologyEn: 'State',
    regionTerminologyAr: 'ولاية',
    regions: [
      {
        id: 'reg-california',
        nameEn: 'California',
        nameAr: 'كاليفورنيا',
        cities: [
          {
            id: 'city-fresno',
            nameEn: 'Fresno (San Joaquin Valley)',
            nameAr: 'فريزنو (وادي سان هواكين)',
            soilTypeEn: 'Fine Sandy Alluvial Loam',
            soilTypeAr: 'طمي رملي ناعم فيضي عالي الجودة',
            climateZoneEn: 'Mediterranean Warm Summer with Drip VRI',
            climateZoneAr: 'متوسطي صيفي دافئ مع ري مقنن',
            avgGdd: 2350,
            avgAnnualRainfallMm: 280,
            primaryCropsEn: ['Processing Tomatoes', 'Almonds', 'Pistachios'],
            primaryCropsAr: ['طماطم تصنيع', 'لوز كاليفورنيا', 'فستق حلبي'],
            coordinates: { lat: 36.746, lng: -119.772 },
          },
          {
            id: 'city-bakersfield',
            nameEn: 'Bakersfield (Kern County)',
            nameAr: 'بيكرسفيلد (مقاطعة كيرن)',
            soilTypeEn: 'Deep Sandy Loam with Calcium Horizons',
            soilTypeAr: 'طمي رملي عميق غني بالكالسيوم',
            climateZoneEn: 'Semi-Arid Central Valley Basin',
            climateZoneAr: 'حوض الوادي الأوسط شبه الجاف',
            avgGdd: 2450,
            avgAnnualRainfallMm: 160,
            primaryCropsEn: ['Table Grapes', 'Carrots', 'Citrus'],
            primaryCropsAr: ['عنب مائدة', 'جزر تصديري', 'موالح'],
            coordinates: { lat: 35.373, lng: -119.018 },
          },
        ],
      },
      {
        id: 'reg-iowa',
        nameEn: 'Iowa',
        nameAr: 'أيوا',
        cities: [
          {
            id: 'city-ames',
            nameEn: 'Ames (Story County)',
            nameAr: 'إيمز',
            soilTypeEn: 'Mollisol Rich Black Humus Loam',
            soilTypeAr: 'تربة سوداء غنية بالدبال والمادة العضوية',
            climateZoneEn: 'Humid Continental Corn Belt',
            climateZoneAr: 'قاري رطب حزام الذرة وفول الصويا',
            avgGdd: 1850,
            avgAnnualRainfallMm: 890,
            primaryCropsEn: ['Hybrid Corn', 'High-Protein Soybeans', 'Rye'],
            primaryCropsAr: ['ذرة هجين', 'فول صويا عالي البروتين', 'شيلم'],
            coordinates: { lat: 42.034, lng: -93.62 },
          },
        ],
      },
    ],
  },
  {
    id: 'country-es',
    code: 'ES',
    nameEn: 'Spain',
    nameAr: 'إسبانيا',
    regionTerminologyEn: 'Region',
    regionTerminologyAr: 'إقليم',
    regions: [
      {
        id: 'reg-andalusia',
        nameEn: 'Andalusia',
        nameAr: 'الأندلس',
        cities: [
          {
            id: 'city-almeria',
            nameEn: 'Almería (Poniente Greenhouses)',
            nameAr: 'المرية (البيوت المحمية الكبرى)',
            soilTypeEn: 'Perlite & Coconut Coir High-Tech Matrix',
            soilTypeAr: 'أوساط هيدروبونيك وبيرلايت وألياف جوز هند',
            climateZoneEn: 'Subtropical Semi-Arid Mediterranean Sea-Breeze',
            climateZoneAr: 'شبه مداري شبه جاف نسيم البحر المتوسط',
            avgGdd: 2600,
            avgAnnualRainfallMm: 200,
            primaryCropsEn: ['Vine Tomatoes', 'Sweet Romano Peppers', 'Zucchini'],
            primaryCropsAr: ['طماطم عناقيد', 'فلفل رومانو حلو', 'كوسة'],
            coordinates: { lat: 36.838, lng: -2.459 },
          },
          {
            id: 'city-seville',
            nameEn: 'Seville (Guadalquivir Valley)',
            nameAr: 'إشبيلية (وادي الوادي الكبير)',
            soilTypeEn: 'Deep Heavy River Loam',
            soilTypeAr: 'طمي نهري عميق عالي الاحتفاظ بالرطوبة',
            climateZoneEn: 'Hot-Summer Mediterranean Basin',
            climateZoneAr: 'متوسطي حار صيفاً',
            avgGdd: 2720,
            avgAnnualRainfallMm: 530,
            primaryCropsEn: ['Extra Virgin Olives (Picual/Arbequina)', 'Citrus', 'Rice'],
            primaryCropsAr: ['زيتون بيكوال وأربيكينا', 'برتقال إشبيلي', 'أرز'],
            coordinates: { lat: 37.389, lng: -5.984 },
          },
        ],
      },
    ],
  },
];
