import { Farm, CropScenario, Product, Order, ProduceListing } from '@/types/nabta';

export const INITIAL_FARMS: Farm[] = [
  {
    id: 'farm-1',
    name: 'Delta Agri-Vanguard Plot 04',
    location: 'Wadi El Natrun, Beheira Governorate',
    country: 'Egypt',
    coordinates: { lat: 30.412, lng: 30.345 },
    areaHectares: 85.0,
    irrigationType: 'Solar-Powered Precision Drip System',
    soil: {
      ph: 6.9,
      ec: 1.35,
      texture: 'Sandy Clay Loam',
      organicMatter: 2.3,
      nitrogenPpm: 46,
      phosphorusPpm: 29,
      potassiumPpm: 215,
      calciumPpm: 380,
      magnesiumPpm: 92,
      salinityRisk: 'Low',
    },
    climate: {
      zone: 'Subtropical Semi-Arid Basin',
      growingDegreeDays: 2480,
      avgSummerTempC: 34.5,
      avgWinterTempC: 15.2,
      annualRainfallMm: 45,
      frostRiskDays: 0,
      currentTempC: 28.4,
      humidityPercent: 44,
      windSpeedKmh: 14.2,
      solarRadiationWm2: 890,
    },
    water: {
      source: 'Deep Eocene Aquifer Well #03',
      allocationM3Ha: 6800,
      qualityEc: 0.82,
      salinityTds: 520,
      reliabilityRating: 'High',
    },
    activeScenarioId: 'scenario-1',
    analysisStatus: 'ANALYZED',
    lastSatellitePass: '2026-09-08 09:14 UTC (Sentinel-2C)',
    ndviAverage: 0.78,
    healthIndex: 94,
  },
  {
    id: 'farm-2',
    name: 'Toshka South Pivot Sector 12',
    location: 'New Valley Toshka Project',
    country: 'Egypt',
    coordinates: { lat: 22.583, lng: 31.842 },
    areaHectares: 240.0,
    irrigationType: 'Center Pivot VRI (Variable Rate Irrigation)',
    soil: {
      ph: 7.4,
      ec: 1.85,
      texture: 'Loamy Sand with Silty Inclusions',
      organicMatter: 1.2,
      nitrogenPpm: 32,
      phosphorusPpm: 22,
      potassiumPpm: 180,
      calciumPpm: 420,
      magnesiumPpm: 110,
      salinityRisk: 'Moderate',
    },
    climate: {
      zone: 'Hyper-Arid Continental Desert',
      growingDegreeDays: 3100,
      avgSummerTempC: 41.2,
      avgWinterTempC: 18.0,
      annualRainfallMm: 12,
      frostRiskDays: 0,
      currentTempC: 33.1,
      humidityPercent: 26,
      windSpeedKmh: 18.5,
      solarRadiationWm2: 980,
    },
    water: {
      source: 'Sheikh Zayed Canal Branch 3',
      allocationM3Ha: 7200,
      qualityEc: 0.65,
      salinityTds: 410,
      reliabilityRating: 'High',
    },
    activeScenarioId: 'scenario-4',
    analysisStatus: 'ANALYZED',
    lastSatellitePass: '2026-09-07 10:20 UTC (Sentinel-2B)',
    ndviAverage: 0.82,
    healthIndex: 91,
  },
  {
    id: 'farm-3',
    name: 'Al-Kharj High-Density Protected Center',
    location: 'Al-Kharj Agricultural Belt',
    country: 'Saudi Arabia',
    coordinates: { lat: 24.150, lng: 47.310 },
    areaHectares: 45.0,
    irrigationType: 'Closed-Loop Hydroponic Recirculation',
    soil: {
      ph: 6.4,
      ec: 1.1,
      texture: 'Engineered Coco-Coir & Perlite Matrix',
      organicMatter: 4.8,
      nitrogenPpm: 60,
      phosphorusPpm: 40,
      potassiumPpm: 280,
      calciumPpm: 450,
      magnesiumPpm: 120,
      salinityRisk: 'Low',
    },
    climate: {
      zone: 'Controlled Environment Greenhouse Complex',
      growingDegreeDays: 2800,
      avgSummerTempC: 25.0,
      avgWinterTempC: 22.0,
      annualRainfallMm: 70,
      frostRiskDays: 0,
      currentTempC: 24.5,
      humidityPercent: 62,
      windSpeedKmh: 8.0,
      solarRadiationWm2: 740,
    },
    water: {
      source: 'Reverse Osmosis Desalination Plant',
      allocationM3Ha: 4200,
      qualityEc: 0.35,
      salinityTds: 190,
      reliabilityRating: 'High',
    },
    activeScenarioId: 'scenario-2',
    analysisStatus: 'ANALYZED',
    lastSatellitePass: '2026-09-08 08:45 UTC (PlanetScope SuperDove)',
    ndviAverage: 0.88,
    healthIndex: 97,
  },
];

export const INITIAL_SCENARIOS: CropScenario[] = [
  {
    id: 'scenario-1',
    farmId: 'farm-1',
    cropName: 'Indeterminate Cluster Tomato',
    variety: 'Tycoon F1 Hybrid',
    season: 'Summer 2026',
    status: 'Selected',
    suitabilityScore: 92,
    whyThisCrop: 'Matches sandy clay loam with exceptional calcium absorption dynamics; thermal degree units align perfectly with rapid flowering and dense cluster set.',
    soilCompatibilityScore: 94,
    climateCompatibilityScore: 91,
    waterCompatibilityScore: 90,
    waterDemandRating: 'Medium',
    waterDemandM3Ha: 5400,
    durationDays: 110,
    expectedProductionTonHa: 78.5,
    estimatedCostPerHa: 4250,
    expectedRevenuePerHa: 14915,
    estimatedProfitPerHa: 10665,
    roiPercent: 251,
    carbonScoreKgPerTon: 84,
    recommendedCategoryIds: ['seeds', 'fertilizers', 'irrigation', 'crop-protection'],
  },
  {
    id: 'scenario-2',
    farmId: 'farm-1',
    cropName: 'Blocky Sweet Bell Pepper',
    variety: 'Sven F1 Yellow / Red',
    season: 'Summer 2026',
    status: 'Analyzed',
    suitabilityScore: 87,
    whyThisCrop: 'High tolerance to solar radiation index; excellent nitrogen-to-potassium conversion efficiency in low-salinity drip conditions.',
    soilCompatibilityScore: 89,
    climateCompatibilityScore: 86,
    waterCompatibilityScore: 86,
    waterDemandRating: 'Medium',
    waterDemandM3Ha: 4900,
    durationDays: 125,
    expectedProductionTonHa: 48.0,
    estimatedCostPerHa: 3800,
    expectedRevenuePerHa: 11520,
    estimatedProfitPerHa: 7720,
    roiPercent: 203,
    carbonScoreKgPerTon: 96,
    recommendedCategoryIds: ['seeds', 'fertilizers', 'greenhouses', 'crop-protection'],
  },
  {
    id: 'scenario-3',
    farmId: 'farm-1',
    cropName: 'Export Grade Strawberry',
    variety: 'Fortuna Day-Neutral',
    season: 'Autumn-Winter 2026',
    status: 'Draft',
    suitabilityScore: 81,
    whyThisCrop: 'Premium price-point potential for European export windows, but requires tighter EC control and chilling hours monitoring.',
    soilCompatibilityScore: 83,
    climateCompatibilityScore: 78,
    waterCompatibilityScore: 82,
    waterDemandRating: 'High',
    waterDemandM3Ha: 6200,
    durationDays: 150,
    expectedProductionTonHa: 34.0,
    estimatedCostPerHa: 6800,
    expectedRevenuePerHa: 17000,
    estimatedProfitPerHa: 10200,
    roiPercent: 150,
    carbonScoreKgPerTon: 112,
    recommendedCategoryIds: ['seeds', 'fertilizers', 'irrigation', 'storage-packaging'],
  },
  {
    id: 'scenario-4',
    farmId: 'farm-2',
    cropName: 'Premium Milling Durum Wheat',
    variety: 'Beni Suef 5 / Misr 3',
    season: 'Winter 2026',
    status: 'Selected',
    suitabilityScore: 95,
    whyThisCrop: 'Optimal fit for wide-span center pivots in Toshka; robust deep-root development with high heat resilience during grain filling.',
    soilCompatibilityScore: 96,
    climateCompatibilityScore: 95,
    waterCompatibilityScore: 94,
    waterDemandRating: 'Low',
    waterDemandM3Ha: 3800,
    durationDays: 135,
    expectedProductionTonHa: 8.2,
    estimatedCostPerHa: 1450,
    expectedRevenuePerHa: 3690,
    estimatedProfitPerHa: 2240,
    roiPercent: 154,
    carbonScoreKgPerTon: 62,
    recommendedCategoryIds: ['seeds', 'fertilizers', 'machinery'],
  },
];

export const INITIAL_PRODUCTS: Product[] = [
  // 1. Seeds
  {
    id: 'prod-seed-01',
    name: 'Tycoon F1 Indeterminate Tomato Seeds',
    category: 'seeds',
    subcategory: 'Hybrid Vegetable Seeds',
    manufacturer: 'Hazera Seeds B.V.',
    supplierName: 'AgroBio International',
    supplierId: 'supp-01',
    countryOfOrigin: 'Netherlands',
    priceUSD: 185.0,
    unit: '1,000 Seeds Canister',
    minOrderQuantity: 5,
    availability: 'In Stock',
    stockQuantity: 420,
    rating: 4.9,
    reviewCount: 48,
    images: [
      'https://images.unsplash.com/photo-1592841200221-a6898f307baa?auto=format&fit=crop&w=800&q=80',
    ],
    description: 'High-vigor indeterminate hybrid tomato seed line engineered for warm-climate field and shade net operations. Exceptional resistance to TYLCV, Nematodes, and Fusarium Wilt Races 1-3.',
    specifications: {
      'Germination Rate': '98.5%',
      'Purity': '99.9%',
      'Fruit Weight': '180 - 220g',
      'Disease Resistances': 'HR: ToMV, Vd, Fol:1,2, For, TYLCV, Mi',
      'Vigor Index': 'High vegetative renewal',
    },
    certifications: ['ISTA Certified', 'Naktuinbouw Elite', 'GLOBALG.A.P. Standard'],
    suitableCrops: ['Tomato', 'Cluster Tomato'],
    suitableSoilConditions: ['pH 6.0 - 7.5', 'Sandy Loam', 'Clay Loam'],
    shippingInformation: 'Direct express air cargo dispatch in climate-shield packaging. Delivered within 3-5 business days.',
    featured: true,
    moderationStatus: 'APPROVED',
    scenarioMatchReason: 'Direct varietal match for your active Tomato Summer 2026 scenario. High tolerance to the 34.5°C peak ambient temperatures recorded on your farm.',
  },
  {
    id: 'prod-seed-02',
    name: 'Sven F1 Blocky Sweet Pepper Seeds',
    category: 'seeds',
    subcategory: 'Capsicum Germplasm',
    manufacturer: 'Enza Zaden',
    supplierName: 'Levant Seed House',
    supplierId: 'supp-02',
    countryOfOrigin: 'Netherlands',
    priceUSD: 210.0,
    unit: '1,000 Seeds Pack',
    minOrderQuantity: 2,
    availability: 'In Stock',
    stockQuantity: 180,
    rating: 4.8,
    reviewCount: 31,
    images: [
      'https://images.unsplash.com/photo-1563565375-f3fdfdbefa83?auto=format&fit=crop&w=800&q=80',
    ],
    description: 'Heavy-yielding four-lobed blocky pepper hybrid. Thick wall geometry provides extraordinary shelf-life and shipping endurance for export logistics.',
    specifications: {
      'Average Fruit Weight': '220 - 260g',
      'Color Transition': 'Dark Green to Bright Deep Yellow',
      'Resistances': 'HR: Tm:0-3, PVY:0,1; IR: TSWV:0',
    },
    certifications: ['ISTA Clean Seed', 'EU Seed Passport'],
    suitableCrops: ['Bell Pepper', 'Sweet Pepper'],
    suitableSoilConditions: ['pH 6.2 - 7.2', 'Well-drained soils'],
    shippingInformation: 'Standard temperature-controlled dispatch.',
    featured: false,
    moderationStatus: 'APPROVED',
  },

  // 2. Fertilizers
  {
    id: 'prod-fert-01',
    name: 'SoluPotash Ultra NPK 12-12-36 + Micronutrients',
    category: 'fertilizers',
    subcategory: 'Water Soluble Fertigation',
    manufacturer: 'Tessenderlo Kerley',
    supplierName: 'EuroAgro Chemical Corp',
    supplierId: 'supp-03',
    countryOfOrigin: 'Belgium',
    priceUSD: 44.5,
    unit: '25kg Polyethylene Bag',
    minOrderQuantity: 20,
    availability: 'In Stock',
    stockQuantity: 1250,
    rating: 4.95,
    reviewCount: 86,
    images: [
      'https://images.unsplash.com/photo-1585314062340-f1a5a7c9328d?auto=format&fit=crop&w=800&q=80',
    ],
    description: 'Fully water-soluble potassium-dominant fertigation formula. Contains chelated iron (EDDHA), zinc, boron, and manganese to supercharge fruit bulking and brix levels.',
    specifications: {
      'Formulation': '12-12-36 + 2MgO + TE',
      'Solubility': '100% free of insoluble particulates',
      'Chloride Content': '< 0.1% (Virtually chlorine-free)',
      'EC (1g/L at 20°C)': '1.28 dS/m',
    },
    certifications: ['REACH Certified', 'ISO 14001', 'Heavy Metal Free Assurance'],
    suitableCrops: ['Tomato', 'Bell Pepper', 'Strawberry', 'Potato', 'Citrus'],
    suitableSoilConditions: ['All drip irrigated soils', 'Low to high salinity'],
    shippingInformation: 'Palletized container load (40 bags / pallet). Sea freight or domestic regional trucking.',
    featured: true,
    moderationStatus: 'APPROVED',
    scenarioMatchReason: 'Essential input for the fruit enlargement phase of your selected Tomato scenario. Corrects soil potassium demand calculated at 215 ppm.',
  },
  {
    id: 'prod-fert-02',
    name: 'Bio-Humic Gold Liquid Organic Conditioner',
    category: 'fertilizers',
    subcategory: 'Soil Biostimulants',
    manufacturer: 'Tradecorp International',
    supplierName: 'Iberian Agro Supplies',
    supplierId: 'supp-04',
    countryOfOrigin: 'Spain',
    priceUSD: 72.0,
    unit: '20L Jerrycan',
    minOrderQuantity: 4,
    availability: 'In Stock',
    stockQuantity: 340,
    rating: 4.7,
    reviewCount: 22,
    images: [
      'https://images.unsplash.com/photo-1615811361523-6bd03d7748e7?auto=format&fit=crop&w=800&q=80',
    ],
    description: 'Concentrated leonardite-derived potassium humate and fulvic acids. Drastically enhances cation exchange capacity (CEC) and unlocks phosphorus tied up in alkaline soils.',
    specifications: {
      'Total Humic Extract': '16.5% w/w (12% Humic, 4.5% Fulvic)',
      'Potassium (K2O)': '5.0% w/w',
      'Density': '1.14 g/cc',
    },
    certifications: ['OMRI Listed', 'ECOCERT Organic Compliant'],
    suitableCrops: ['All Horticulture', 'Field Crops', 'Orchards'],
    suitableSoilConditions: ['Sandy soils', 'Low organic matter (< 2.5%)'],
    shippingInformation: 'Liquid bulk or palletized shipping container.',
    featured: false,
    moderationStatus: 'APPROVED',
    scenarioMatchReason: 'Directly addresses your soil’s 2.3% organic matter baseline, boosting nutrient absorption efficiency by up to 24%.',
  },

  // 3. Crop Protection
  {
    id: 'prod-prot-01',
    name: 'Bacillus Subtilis QST 713 Bio-Fungicide',
    category: 'crop-protection',
    subcategory: 'Biological Pest Management',
    manufacturer: 'Bayer Crop Science',
    supplierName: 'Middle East BioDefense',
    supplierId: 'supp-05',
    countryOfOrigin: 'Germany',
    priceUSD: 115.0,
    unit: '5L Container',
    minOrderQuantity: 2,
    availability: 'In Stock',
    stockQuantity: 210,
    rating: 4.9,
    reviewCount: 39,
    images: [
      'https://images.unsplash.com/photo-1530836369250-ef72a3f5cda8?auto=format&fit=crop&w=800&q=80',
    ],
    description: 'High-potency biological bactericide and fungicide. Controls early blight, powdery mildew, and bacterial spot without harvest withholding periods (0-day PHI).',
    specifications: {
      'Active Organism': 'Bacillus amyloliquefaciens strain QST 713',
      'Viable Spores': 'Min 1.0 x 10^9 CFU/g',
      'Pre-Harvest Interval (PHI)': '0 Days',
      'Re-Entry Interval (REI)': '4 Hours',
    },
    certifications: ['EPA Registered', 'GLOBALG.A.P. MRL-Exempt', 'OMRI Organic'],
    suitableCrops: ['Tomato', 'Bell Pepper', 'Grapes', 'Strawberries', 'Cucurbits'],
    suitableSoilConditions: ['Universal foliar & root drench'],
    shippingInformation: 'Temperature stabilized storage during transit (below 30°C).',
    featured: true,
    moderationStatus: 'APPROVED',
    scenarioMatchReason: 'Zero-residue protection safeguard required for GLOBALG.A.P. export compliance under your Tomato scenario.',
  },

  // 4. Irrigation
  {
    id: 'prod-irrig-01',
    name: 'UniRam Heavy-Wall Pressure-Compensating Drip Line',
    category: 'irrigation',
    subcategory: 'Precision Drip Tubing',
    manufacturer: 'Netafim Ltd.',
    supplierName: 'Delta Agri-Tech Systems',
    supplierId: 'supp-06',
    countryOfOrigin: 'Israel / Egypt Plant',
    priceUSD: 135.0,
    unit: '500m Roll',
    minOrderQuantity: 6,
    availability: 'In Stock',
    stockQuantity: 520,
    rating: 4.95,
    reviewCount: 74,
    images: [
      'https://images.unsplash.com/photo-1563514227147-6d2ff665a6a0?auto=format&fit=crop&w=800&q=80',
    ],
    description: 'Pressure-compensating, anti-siphon continuous self-cleaning drip line. Ideal for uneven field topography and long lateral runs with 100% emission uniformity.',
    specifications: {
      'Emitter Flow Rate': '1.60 L/h',
      'Emitter Spacing': '30 cm',
      'Wall Thickness': '1.0 mm (40 mil)',
      'Pressure Compensation Range': '0.5 to 4.0 Bar',
    },
    certifications: ['ISO 9261 Compliant', 'UV Resistance ASTM G154'],
    suitableCrops: ['Row Crops', 'Tomato', 'Pepper', 'Melon', 'Orchards'],
    suitableSoilConditions: ['All soil profiles'],
    shippingInformation: 'Coiled rolls palletized. Heavy equipment logistics.',
    featured: true,
    moderationStatus: 'APPROVED',
    scenarioMatchReason: 'Guarantees the exact 5,400 m3/ha seasonal water schedule required by your selected Tomato scenario with 96% coefficient of uniformity.',
  },

  // 5. Sensors & IoT
  {
    id: 'prod-iot-01',
    name: 'TerraSense Pro 10-Depth Soil Telemetry Probe',
    category: 'sensors-iot',
    subcategory: 'IoT Sub-Surface Telemetry',
    manufacturer: 'Sentek Technologies',
    supplierName: 'AeroPulse Agronomics',
    supplierId: 'supp-07',
    countryOfOrigin: 'Australia / USA',
    priceUSD: 850.0,
    unit: 'Complete Solar Probe Station',
    minOrderQuantity: 1,
    availability: 'In Stock',
    stockQuantity: 65,
    rating: 4.9,
    reviewCount: 19,
    images: [
      'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=800&q=80',
    ],
    description: 'Cellular 4G/NB-IoT multi-depth capacitance probe measuring volumetric soil water content, salinity (bulk EC), and temperature every 10cm down to 100cm depth.',
    specifications: {
      'Sensors': '10 multi-frequency capacitive rings',
      'Telemetry': '4G LTE-M / NB-IoT with fallback',
      'Power': 'Integrated solar panel with 5-year lithium pack',
      'Ingress Protection': 'IP68 Submersible enclosure',
    },
    certifications: ['FCC Certified', 'CE Mark', 'RoHS Compliant'],
    suitableCrops: ['All automated irrigation operations'],
    suitableSoilConditions: ['Calibrated for sandy, loam, and clay matrices'],
    shippingInformation: 'Air courier with calibrated soil drill kit.',
    featured: true,
    moderationStatus: 'APPROVED',
  },

  // 6. Machinery
  {
    id: 'prod-mach-01',
    name: 'AgBot Apex Autonomous Field Scout & Spray Drone',
    category: 'machinery',
    subcategory: 'UAV & Autonomous Systems',
    manufacturer: 'DJI Agriculture',
    supplierName: 'Gulf Drone Technologies',
    supplierId: 'supp-08',
    countryOfOrigin: 'UAE / China',
    priceUSD: 14500.0,
    unit: 'Turnkey UAV System with 3 Batteries & Hub',
    minOrderQuantity: 1,
    availability: 'Low Stock',
    stockQuantity: 8,
    rating: 4.85,
    reviewCount: 14,
    images: [
      'https://images.unsplash.com/photo-1527977966376-1c8408f9f108?auto=format&fit=crop&w=800&q=80',
    ],
    description: 'Heavy payload 40L autonomous agricultural drone equipped with dual atomizing centrifugal nozzles and active phased array radar for millimeter terrain following.',
    specifications: {
      'Spray Tank Capacity': '40 Liters',
      'Max Spray Width': '11 Meters',
      'Field Efficiency': '21 Hectares / Hour',
      'Obstacle Avoidance': 'Omnidirectional 360 radar + binocular vision',
    },
    certifications: ['Civil Aviation Approved', 'CE Machinery Directive', 'IPX6K Washable'],
    suitableCrops: ['Field Crops', 'Vegetables', 'Orchards'],
    suitableSoilConditions: ['Universal'],
    shippingInformation: 'Reinforced hard flight cases via freight forwarding.',
    featured: false,
    moderationStatus: 'APPROVED',
  },

  // 7. Greenhouses
  {
    id: 'prod-green-01',
    name: 'Gothic Arch Climate-Shield Multi-Span Greenhouse',
    category: 'greenhouses',
    subcategory: 'Protected Horticulture Infrastructure',
    manufacturer: 'Richel Group',
    supplierName: 'Mediterranean Greenhouse Engineering',
    supplierId: 'supp-09',
    countryOfOrigin: 'France',
    priceUSD: 38000.0,
    unit: '1 Hectare Modular Structure Kit',
    minOrderQuantity: 1,
    availability: 'Pre-Order',
    stockQuantity: 12,
    rating: 4.9,
    reviewCount: 11,
    images: [
      'https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?auto=format&fit=crop&w=800&q=80',
    ],
    description: 'High-tunnel 9.6m bay gothic steel structure with motorized ridge vents, double inflated thermal PE film, and automated shade screening for arid regions.',
    specifications: {
      'Bay Width': '9.60 Meters',
      'Gutter Height': '5.00 Meters',
      'Ridge Height': '7.50 Meters',
      'Wind Load Resistance': '140 km/h engineered rating',
    },
    certifications: ['Eurocode 13031-1', 'Galvanized EN 1461'],
    suitableCrops: ['Tomato', 'Bell Pepper', 'Cucumber', 'Berries'],
    suitableSoilConditions: ['Soil or Soilless / Hydroponic foundations'],
    shippingInformation: 'Flat-packed container shipment (2 x 40ft HQ containers).',
    featured: false,
    moderationStatus: 'APPROVED',
  },

  // 8. Storage & Packaging
  {
    id: 'prod-pack-01',
    name: 'Ventilated AgriPlast Heavy Export Bins (600L)',
    category: 'storage-packaging',
    subcategory: 'Harvest Logistics & Cold Chain',
    manufacturer: 'Schoeller Allibert',
    supplierName: 'Global Packaging Logix',
    supplierId: 'supp-10',
    countryOfOrigin: 'Germany',
    priceUSD: 140.0,
    unit: 'Stackable HDPE Bin (1200 x 1000 x 760mm)',
    minOrderQuantity: 10,
    availability: 'In Stock',
    stockQuantity: 450,
    rating: 4.8,
    reviewCount: 26,
    images: [
      'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=800&q=80',
    ],
    description: 'Food-grade high-density polyethylene ventilated harvest containers. Engineered for maximum airflow in cold storage pre-cooling tunnels with 4.5-ton stack rating.',
    specifications: {
      'Volume': '610 Liters',
      'Load Capacity': '500 kg dynamic, 4,500 kg static',
      'Material': 'Virgin HDPE Food Grade with UV Stabilizers',
    },
    certifications: ['FDA Food Contact Compliant', 'ISO 22000', 'BPA Free'],
    suitableCrops: ['Fresh produce', 'Tomato', 'Citrus', 'Onions', 'Potatoes'],
    suitableSoilConditions: ['Universal harvest operations'],
    shippingInformation: 'Stackable nesting for volume-efficient freight.',
    featured: false,
    moderationStatus: 'APPROVED',
  },

  // 9. Farm Produce (Direct from verified growers)
  {
    id: 'prod-harvest-01',
    name: 'GlobalGAP Certified Cluster Tomatoes (Grade A Export)',
    category: 'farm-produce',
    subcategory: 'Fresh Commercial Harvest',
    manufacturer: 'Delta Agri-Vanguard Farm 04',
    supplierName: 'Osama Farouk Agricultural Operations',
    supplierId: 'farmer-01',
    countryOfOrigin: 'Egypt',
    priceUSD: 680.0,
    unit: 'Metric Ton (Palletized 5kg boxes)',
    minOrderQuantity: 5,
    availability: 'Pre-Order',
    stockQuantity: 120,
    rating: 5.0,
    reviewCount: 7,
    images: [
      'https://images.unsplash.com/photo-1592924357228-91a4daadcfea?auto=format&fit=crop&w=800&q=80',
    ],
    description: 'Export-grade vine-ripened cluster tomatoes harvested at color stage 3-4. Zero chemical residue above EU MRL benchmarks; cold-chain pre-cooled at 12°C within 2 hours of picking.',
    specifications: {
      'Brix': '5.4° - 6.2°',
      'Diameter': '57 - 67 mm (Caliber M)',
      'Firmness': '> 65 Durofel Index',
      'Harvest Window': 'November 2026 - January 2027',
    },
    certifications: ['GLOBALG.A.P. IFA v6', 'SMETA Ethical Audit', 'GRASP Certified'],
    suitableCrops: ['Wholesale distribution', 'Supermarket retail chains'],
    suitableSoilConditions: ['N/A (Harvested product)'],
    shippingInformation: 'Reefer container (CA / Controlled Atmosphere) dispatch from Port Said / Alexandria.',
    featured: true,
    moderationStatus: 'APPROVED',
    producerHarvestDate: '2026-11-15',
  },
];

export const INITIAL_ORDERS: Order[] = [
  {
    id: 'ORD-2026-8941',
    date: '2026-09-04',
    customerName: 'Eng. Osama Farouk',
    customerEmail: 'osama.farouk@agri-vanguard.com',
    deliveryAddress: {
      street: 'Wadi El Natrun Agro-Zone 4, KM 108',
      city: 'Sadat City District',
      region: 'Beheira Governorate',
      country: 'Egypt',
      postalCode: '32958',
    },
    items: [
      {
        product: INITIAL_PRODUCTS[0], // Tycoon F1 Seeds
        quantity: 10,
      },
      {
        product: INITIAL_PRODUCTS[2], // SoluPotash
        quantity: 40,
      },
      {
        product: INITIAL_PRODUCTS[4], // Bio-Fungicide
        quantity: 4,
      },
    ],
    subtotalUSD: 4090.0,
    shippingUSD: 180.0,
    totalUSD: 4270.0,
    paymentMethod: 'Verified Agricultural Escrow (NABTA Secure)',
    status: 'In Transit',
    estimatedDeliveryDate: '2026-09-12',
    trackingNumber: 'NABTA-EXP-7729104',
  },
  {
    id: 'ORD-2026-8420',
    date: '2026-08-22',
    customerName: 'Eng. Osama Farouk',
    customerEmail: 'osama.farouk@agri-vanguard.com',
    deliveryAddress: {
      street: 'Wadi El Natrun Agro-Zone 4, KM 108',
      city: 'Sadat City District',
      region: 'Beheira Governorate',
      country: 'Egypt',
      postalCode: '32958',
    },
    items: [
      {
        product: INITIAL_PRODUCTS[5], // UniRam Drip Line
        quantity: 12,
      },
      {
        product: INITIAL_PRODUCTS[3], // Bio-Humic Gold
        quantity: 8,
      },
    ],
    subtotalUSD: 2196.0,
    shippingUSD: 120.0,
    totalUSD: 2316.0,
    paymentMethod: 'Bank Wire Transfer',
    status: 'Delivered',
    estimatedDeliveryDate: '2026-08-28',
    trackingNumber: 'NABTA-EXP-6638101',
  },
];

export const INITIAL_PRODUCE_LISTINGS: ProduceListing[] = [
  {
    id: 'listing-01',
    farmerName: 'Osama Farouk',
    farmName: 'Delta Agri-Vanguard Plot 04',
    productName: 'Export Grade Vine Tomatoes',
    variety: 'Tycoon F1',
    quantityTons: 120,
    location: 'Wadi El Natrun, Egypt',
    pricePerTonUSD: 680,
    harvestDate: '2026-11-15',
    images: ['https://images.unsplash.com/photo-1592924357228-91a4daadcfea?auto=format&fit=crop&w=800&q=80'],
    description: 'High-firmness vine-ripened tomatoes grown under precision drip fertigation with integrated pest management.',
    certifications: ['GLOBALG.A.P.', 'GRASP'],
    availability: 'Upcoming Harvest',
    status: 'Active',
  },
  {
    id: 'listing-02',
    farmerName: 'Ahmed Al-Mansoor',
    farmName: 'Al-Kharj High-Density Center',
    productName: 'Hydroponic Sweet Yellow Peppers',
    variety: 'Sven F1',
    quantityTons: 45,
    location: 'Al-Kharj, Saudi Arabia',
    pricePerTonUSD: 1450,
    harvestDate: '2026-10-01',
    images: ['https://images.unsplash.com/photo-1563565375-f3fdfdbefa83?auto=format&fit=crop&w=800&q=80'],
    description: 'Export-certified greenhouse hydroponic peppers with zero soil contact and immaculate grade A calibration.',
    certifications: ['Saudi GAP', 'ISO 22000'],
    availability: 'Upcoming Harvest',
    status: 'Active',
  },
];
